---
- name: 'Cau hinh Switch'
  hosts: all
  gather_facts: no
  
  tasks: 
    - name: show ip
    cisco.ios.ios_command:
      commands: show ip int br
      register: output

    - debug: var=output.stdout_lines