---
- name: 'Cau hinh Switch'
  hosts: all
  gather_facts: no
  
  tasks: 
    - name: Tao Loopback
      ios_interface:
        name: Loopback100
        state: up

  
    - name: show ip
      ios_command:
        commands: show ip int br
      register: output

    - debug: var=output.stdout_lines